### PR TITLE
feat(iam): Add AWS Glue Policy to the IAM Role

### PR DESCRIPTION
**Pull request by morazow**
Add AWS Glue policies:

```
      "glue:GetDatabase",
      "glue:CreateDatabase",
      "glue:GetTable",
      "glue:CreateTable",
      "glue:GetTables"
```

To the private connections IAM role.

### CODE REVIEW

**Comment by webertrlz** [comment]
thanks @morazow  - can you update the commit message to use semantic commit? Suggestion: the same as the PR title.

**Comment by morazow** [comment]
Thanks @webertrlz, done!

**Comment by webertrlz** [comment]
Can you do `terraform fmt modules/private-connection/iam.tf` to fix the failing check?

**Comment by morazow** [comment]
Done, thanks @webertrlz

**Review by webertrlz — APPROVED** [review]

**Review by webertrlz — APPROVED** [review]

**Pull request merged**
